from MiraExternals import *
#himitsu = [[[[['[[\'TOTAL_ARGUMENT == \\\'print("'], ['[[\'TOTAL_ARGUMENT == \\\'print("']], [['α0'], ['α0']], [['")\\\'\', \'None\']]'], ['")\\\'\', \'None\']]']]]], [[[['[[\'TOTAL_ARGUMENT == \\\'print("'], ['[[\'TOTAL_ARGUMENT == \\\'print("']], [['α0'], ['α0']], [['t")\\\'\', \'None\']]'], ['t")\\\'\', \'None\']]']]]], [[[['[['], ['[[']], [['α0'], ['α0']], [['TOTAL_ARGUMENT == '], ['TOTAL_ARGUMENT == ']], [['α1'], ['α1']], [['test'], ['test']], [['α2'], ['α2']]]], [[[['[['], ['[[']], [['α0'], ['α0']], [['TOTAL_ARGUMENT == '], ['TOTAL_ARGUMENT == ']], [['α1'], ['α1']], [[", '"], [", '"]], [['α2'], ['α2']]]], [[[['[[\'TOTAL_ARGUMENT == \\\'print("'], ['[[\'TOTAL_ARGUMENT == \\\'print("']], [['r")\\\'\', \'None\']]'], ['r")\\\'\', \'None\']]']]]], [[[['[['], ['[[']], [['α0'], ['α0']], [['TOTAL_ARGUMENT == '], ['TOTAL_ARGUMENT == ']], [['α1'], ['α1']], [["'', "], ["'', "]], [['α2'], ['α2']]]], [[[['[[\'TOTAL_ARGUMENT == \\\'print("r'], ['[[\'TOTAL_ARGUMENT == \\\'print("r']], [['")\\\'\', \'None\']]'], ['")\\\'\', \'None\']]']]]], [[[['[[\'TOTAL_ARGUMENT == \\\'print("'], ['[[\'TOTAL_ARGUMENT == \\\'print("']], [['f")\\\'\', \'None\']]'], ['f")\\\'\', \'None\']]']]]], [[[['[[\'TOTAL_ARGUMENT == \\\'print("f'], ['[[\'TOTAL_ARGUMENT == \\\'print("f']], [['")\\\'\', \'None\']]'], ['")\\\'\', \'None\']]']]]], [[[['[[\'TOTAL_ARGUMENT == \\\'print("buk'], ['[[\'TOTAL_ARGUMENT == \\\'print("buk']], [['α0'], ['α0']], [['")\\\'\', \'None\']]'], ['")\\\'\', \'None\']]']]]], [[[['[[\'TOTAL_ARGUMENT == \\\'print("bukD'], ['[[\'TOTAL_ARGUMENT == \\\'print("bukD']], [['")\\\'\', \'None\']]'], ['")\\\'\', \'None\']]']]]], [[[['[[\'TOTAL_ARGUMENT == \\\'print("'], ['[[\'TOTAL_ARGUMENT == \\\'print("']], [['α0'], ['α0']], [['ect")\\\'\', \'None\']]'], ['ect")\\\'\', \'None\']]']]]], [[[['[[\'TOTAL_ARGUMENT == \\\'print("'], ['[[\'TOTAL_ARGUMENT == \\\'print("']], [['α0'], ['α0']], [['l")\\\'\', \'None\']]'], ['l")\\\'\', \'None\']]']]]], [[[['[[\'TOTAL_ARGUMENT == \\\'print("r'], ['[[\'TOTAL_ARGUMENT == \\\'print("r']], [['α0'], ['α0']], [['")\\\'\', \'None\']]'], ['")\\\'\', \'None\']]']]]], [[[['[["TOTAL_ARGUMENT == \''], ['[["TOTAL_ARGUMENT == \'']], [['α0'], ['α0']], [['\'", '], ['\'", ']], [['α1'], ['α1']]]], [[[['[["TOTAL_ARGUMENT == \''], ['[["TOTAL_ARGUMENT == \'']], [['α0'], ['α0']], [['\'", \''], ['\'", \'']], [['α1'], ['α1']]]], [[[['[["TOTAL_ARGUMENT == \'1+'], ['[["TOTAL_ARGUMENT == \'1+']], [['α0'], ['α0']], [['\'", \''], ['\'", \'']], [['α1'], ['α1']]]], [[[['[["TOTAL_ARGUMENT == \''], ['[["TOTAL_ARGUMENT == \'']], [['α0'], ['α0']], [['+5\'", \''], ['+5\'", \'']], [['α1'], ['α1']]]]]
#himitsu = [[[['[[\'TOTAL_ARGUMENT == \\\'print("'], ['[[\'TOTAL_ARGUMENT == \\\'print("']], [['α0'], ['α0']], [['")\\\'\', \'None\']]'], ['")\\\'\', \'None\']]']]], [[['[[\'TOTAL_ARGUMENT == \\\'print("'], ['[[\'TOTAL_ARGUMENT == \\\'print("']], [['α0'], ['α0']], [['t")\\\'\', \'None\']]'], ['t")\\\'\', \'None\']]']]], [[['[['], ['[[']], [['α0'], ['α0']], [['TOTAL_ARGUMENT == '], ['TOTAL_ARGUMENT == ']], [['α1'], ['α1']], [['test'], ['test']], [['α2'], ['α2']]], [[['[['], ['[[']], [['α0'], ['α0']], [['TOTAL_ARGUMENT == '], ['TOTAL_ARGUMENT == ']], [['α1'], ['α1']], [[", '"], [", '"]], [['α2'], ['α2']]], [[['[['], ['[[']], [['α0'], ['α0']], [['TOTAL_ARGUMENT == '], ['TOTAL_ARGUMENT == ']], [['α1'], ['α1']], [["'', "], ["'', "]], [['α2'], ['α2']]], [[['[["TOTAL_ARGUMENT == \''], ['[["TOTAL_ARGUMENT == \'']], [['α0'], ['α0']], [['\'", '], ['\'", ']], [['α1'], ['α1']]], [[['[["TOTAL_ARGUMENT == \''], ['[["TOTAL_ARGUMENT == \'']], [['α0'], ['α0']], [['\'", \''], ['\'", \'']], [['α1'], ['α1']]], [[['[["TOTAL_ARGUMENT == \'1+'], ['[["TOTAL_ARGUMENT == \'1+']], [['α0'], ['α0']], [['\'", \''], ['\'", \'']], [['α1'], ['α1']]], [[['[["TOTAL_ARGUMENT == \''], ['[["TOTAL_ARGUMENT == \'']], [['α0'], ['α0']], [['+5\'", \''], ['+5\'", \'']], [['α1'], ['α1']]]]
#himitsu = [[[['[[\'TOTAL_ARGUMENT == \\\'print("α0'], ['[[\'TOTAL_ARGUMENT == \\\'print("α0']], [['")\\\'\', \'None\']]'], ['")\\\'\', \'None\']]']]], [[['[['], ['[[']], [['α0'], ['α0']], [['TOTAL_ARGUMENT == '], ['TOTAL_ARGUMENT == ']], [['α'], ['α']], [['α1'], ['α1']]], [[['[['], ['[[']], [['α0'], ['α0']], [['TOTAL_ARGUMENT == '], ['TOTAL_ARGUMENT == ']], [['α1'], ['α1']], [[", '"], [", '"]], [['α2'], ['α2']]], [[['[['], ['[[']], [['α0'], ['α0']], [['TOTAL_ARGUMENT == '], ['TOTAL_ARGUMENT == ']], [['α1'], ['α1']], [["'', "], ["'', "]], [['α2'], ['α2']]], [[['[['], ['[[']], [['α0'], ['α0']], [['TOTAL_ARGUMENT == '], ['TOTAL_ARGUMENT == ']], [['α1'], ['α1']], [['α0'], ['α0']], [['α2'], ['α2']]], [[['[['], ['[[']], [['α0'], ['α0']], [['TOTAL_ARGUMENT == '], ['TOTAL_ARGUMENT == ']], [['α1'], ['α1']]]]
#himitsu = [[[['[[\'TOTAL_ARGUMENT == \\\'print("'], ['[[\'TOTAL_ARGUMENT == \\\'print("']], [['α0'], ['α0']], [['")\\\'\', \'None\']]'], ['")\\\'\', \'None\']]']]], [[['[[\'TOTAL_ARGUMENT == \\\'print("'], ['[[\'TOTAL_ARGUMENT == \\\'print("']], [['α0'], ['α0']], [['t")\\\'\', \'None\']]'], ['t")\\\'\', \'None\']]']]], [[['[[\'TOTAL_ARGUMENT == \\\'print("buk'], ['[[\'TOTAL_ARGUMENT == \\\'print("buk']], [['α0'], ['α0']], [['")\\\'\', \'None\']]'], ['")\\\'\', \'None\']]']]], [[['[[\'TOTAL_ARGUMENT == \\\'print("'], ['[[\'TOTAL_ARGUMENT == \\\'print("']], [['α0'], ['α0']], [['ect")\\\'\', \'None\']]'], ['ect")\\\'\', \'None\']]']]], [[['[[\'TOTAL_ARGUMENT == \\\'print("'], ['[[\'TOTAL_ARGUMENT == \\\'print("']], [['α0'], ['α0']], [['l")\\\'\', \'None\']]'], ['l")\\\'\', \'None\']]']]], [[['[[\'TOTAL_ARGUMENT == \\\'print("r'], ['[[\'TOTAL_ARGUMENT == \\\'print("r']], [['α0'], ['α0']], [['")\\\'\', \'None\']]'], ['")\\\'\', \'None\']]']]], [[['[[\'TOTAL_ARGUMENT == \\\'print("w'], ['[[\'TOTAL_ARGUMENT == \\\'print("w']], [['α0'], ['α0']], [['")\\\'\', \'None\']]'], ['")\\\'\', \'None\']]']]], [[['[[\'TOTAL_ARGUMENT == \\\'print("da'], ['[[\'TOTAL_ARGUMENT == \\\'print("da']], [['α0'], ['α0']], [['")\\\'\', \'None\']]'], ['")\\\'\', \'None\']]']]], [[['[[\'TOTAL_ARGUMENT == \\\'print("'], ['[[\'TOTAL_ARGUMENT == \\\'print("']], [['α0'], ['α0']], [['i")\\\'\', \'None\']]'], ['i")\\\'\', \'None\']]']]], [[['[[\'TOTAL_ARGUMENT == \\\'print("'], ['[[\'TOTAL_ARGUMENT == \\\'print("']], [['α0'], ['α0']], [['")\\\'\', \'None\']]'], ['")\\\'\', \'None\']]']]]]
himitsu = [[[['dot', 'dot']], '0'], [[['linea', 'lineb']], '1'], [[['triaX', 'triaY'], ['triaY', 'triaZ'], ['triaZ', 'triaX']], '2'], [[[['dot', 'dot']], [['dot', 'dot']]], '3'], [[[['linea', 'lineb']], [['linea', 'lineb']]], '4'], [[[['triaX', 'triaY'], ['triaY', 'triaZ'], ['triaZ', 'triaX']], [['triaX', 'triaY'], ['triaY', 'triaZ'], ['triaZ', 'triaX']]], '5'], ['0', '6'], ['1', '7'], ['2', '8']]
garbanzo = []

for x in himitsu:
    print(x)
    #print(toString([ran(x),"naive"]))



